#!/bin/sh
set -e

case "$1" in
    configure)
        update-desktop-database /usr/share/applications
        gtk-update-icon-cache
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
