#!/bin/bash
set -e

case "$1" in
    configure)
        # remove electron app cache
        RUID=$(who | awk 'FNR == 1 {print $1}')
        RUSER_UID=$(id -u ${RUID})
        if [ -d "/home/${RUID}/.config/ActivityWatch" ]; then
            echo "Remove App Cache..."
            rm -rf /home/${RUID}/.config/ActivityWatch
        fi

        update-desktop-database /usr/share/applications
        gtk-update-icon-cache
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
